name: Rust

on:
    push:
    pull_request:

jobs:
    rust:
        runs-on: ubuntu-latest
        container:
            image: fedora:latest
            options: --privileged
        steps:
            - name: Run workflow
              uses: FyraLabs/actions/.github/workflows/rust.yml@main
              
